site_name: django-testing-base
theme: readthedocs
repo_url: https://github.com/tctimmeh/django-testing-base
pages:
- [index.md, Django Testing Base, Overview]
- [base.md, Django Testing Base, Base Test Case]
- [unit/unit.md, Unit Test Case, Unit Test Case]
- [unit/mixin.md, Unit Test Case, Mixins]
- [browser/pageobject.md, Browser Test Case, Page Object]
- [browser/browser.md, Browser Test Case, Browser Test Case]
